campaign_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('campaign-management/', include('campaign_management.urls', namespace='campaign_management'), name='campaign_management'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaign_management/urls.py
from django.urls import path
from .views import *
from django.utils.decorators import method_decorator
from .decorators import redirect_if_logged_in
app_name = "campaign_management"

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout',LogoutView.as_view(),name="logout"),   
    # path('sign-up/', add_user, name="sign_up" ),

    path('list-contacts/', list_contacts, name="list_contacts"),
    path('add-contact/', add_contact, name="add_contact"),
    path('edit-contact/pk=<int:pk>', edit_contact , name="edit_contact"),
    path('delete-contact/pk=<int:pk>', delete_contact , name="delete_contact"),
    path('sync-contacts/', sync_contacts, name='sync_contacts'),
    path('add-campaign/', add_campaign, name="add_campaign"),
    path('list-campaign/', list_campaigns, name="list_campaigns"),

    path('list-prev-campaigns/', list_prev_campaigns, name="list_prev_campaigns"),

    path('client-search/', client_search, name="client_search"),

] 

templates/add_contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} <title>contact</title> {% endblock title %}

{% block css %}
<style>
    /* Style the file input to be hidden */
    #fileInput {
        display: none;
    }

    /* Style the button to your desired appearance */
    .btn {
        background-color: #28a745;
        color: #fff;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
    }

    /* Style the file name display */
    #fileNameDisplay {
        margin-top: 10px;
    }
</style>
{% endblock css %}
{% block body %}

<main>
    <div class="container-xl px-5">
        <div class="d-flex mt-4 mb-2 align-content-center">
            <h1 class="mb-0">Add Contact</h1>
        </div>
        <div class="tab-content mb-5 mt-5">
            <div class="tab-pane show active">
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} col-md-8" {% endif %} role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}

                <div class="border  p-3 p-sm-5 col-md-8">
                    <form method="POST" action="">
                        {% csrf_token %}
                        {{form|crispy}}
                        <div class="mt-3" style="
                            display: flex;
                            flex-direction: row;
                            justify-content: flex-end;">
                            <button class="btn btn-success" type="submit">
                                Create
                            </button>

                        </div>
                    </form>
                    
                    <label >Create Contacts by Uploding CSV File</label>
                    <div class="mt-3" style="
                            display: flex;
                            flex-direction: column;
                            align-items: flex-start;">
                        <!-- <button class="btn btn-success" type="file">
                            <input  type="file" id="fileInput" name="fileInput">
                            Upload Format
                            <!-- Button to trigger file selection -->
                            <!-- <label for="fileInput" class="btn">Upload Format</label> -->
                        <!-- </button> -->
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="file" name="csv_file">
                            <button class="btn-small btn-success"  type="submit">Upload</button>
                        </form>
                    </div>


                    
                </div>
            </div>

            <!-- Hidden file input
            <input type="file" id="fileInput" name="fileInput">
            <button class="btn btn-success" type="submit">
                Upload Format
            </button> -->
            <div class="mb-5"></div>
        </div>
</main>

{% endblock body %}

templates/edit_contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<title> Edit Contact </title> 
{% endblock title %}

{% block body %}
<main>
    <div class="container-xl px-5">
        <div class="d-flex mt-4 mb-2 align-items-center">
            <h1 class="mb-0">Edit Contact</h1>
        </div>
        <div class="tab-content mb-5 mt-5">
            <div class="tab-pane show active" >
                {% if messages %}
                       
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }} col-md-8"{% endif %}  role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
           
                {% endif %}
                <div class="border border-top-0 p-3 p-sm-5 col-md-8">
                    <form method="POST" action="">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="mt-3" style="
                        display: flex;
                        flex-direction: row;
                        justify-content: flex-end;">
                        <button class="btn btn-primary " type="submit">
                            Edit Contact
                        </button>
                    </div>
                </form>
                </div>
            </div>
            
        <div class="mb-5"></div>
    </div>
</main>

{% endblock body %}

templates/email_template.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ email_subject }}</title>
</head>
<body>
    <p><strong>Dear {{ recipient_name }},</strong></p>
    {{ email_text|safe }}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
<title>Home Page</title>
{% endblock title %}

{% block body %}
<div class="container">
    <div class="row justify-content-center  mt-5">
        <div class="col-md-6">
            
                <div class=" text-center">
                    <h1 class="display-4">Welcome to Campaign App</h1>
                </div>
            
        </div>
    </div>
</div>
{% endblock body %}

templates/list_campaign.html
{% extends "base.html" %}

{% block title %}
<title>list Campaigns</title>
{% endblock title %}

{% block body %}

<main>
    <div class="container-xl px-5">
        <div class="d-flex mt-4 mb-4 align-items-center">
            <h1 class="mb-0 text-center">Campaign Succeed Contact Messages</h1>
        </div>
        <div class="dataTable-wrapper dataTable-loading no-footer sortable searchable fixed-columns">
            {% if messages %}

            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }} col-md-12" {% endif %} role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}

           <!-- Add the dropdown above the table -->
            <!-- <div class="mb-3">
                <label for="campaignSelect" class="form-label">Select Campaign:</label>
                <select class="form-select" id="campaignSelect" name="campaign">
                    <option value="" {% if not selected_campaign_id %} selected {% endif %}>All Campaigns</option>
                    {% for campaign in campaigns %}
                    <option value="{{ campaign.id }}" {% if selected_campaign_id == campaign.id %} selected {% endif %}>{{ campaign.name}} - {{ campaign.type}}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-primary mt-3">Filter</button>
            </div> -->

             <!-- Add the form element to wrap the dropdown and filter button -->
            <form method="GET" action="{% url 'campaign_management:list_campaigns' %}">
                <div class="mb-3">
                    <label for="campaignSelect" class="form-label">Select Campaign:</label>
                    <select class="form-select" id="campaignSelect" name="campaign">
                        <option value="" {% if not selected_campaign_id %} selected {% endif %}>All Campaigns</option>
                        {% for campaign in campaigns %}
                        <option value="{{ campaign.id }}" {% if selected_campaign_id == campaign.id %} selected {% endif %}>{{ campaign.name}} - {{ campaign.type}}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-primary mt-3">Filter</button>
                </div>
            </form>


            <!-- dataTable-table -->
            <div class="dataTable-container">
                <table id="datatablesSimple" class="dataTable-table">
                    <thead>
                        <tr>
                            <th><a href="#">Campaign Name </a></th>
                            <th><a href="#">Campaign Type</a></th>
                            <th><a href="#">Campaign Status</a></th>
                            <th><a href="#">Contact Name</a></th>
                            <th><a href="#">Contact Email</a></th>
                            <th><a href="#">Contact Phone Number</a></th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for campaign_msgs in campaign_msgs_items_paginator %}
                        <tr>
                            <td>{{campaign_msgs.campaign.name}}</td>
                            <td>{{campaign_msgs.campaign.type}}</td>
                            <td>{{campaign_msgs.contacts.status}}</td>
                            <td>{{campaign_msgs.contacts.name}}</td>
                            <td>{{campaign_msgs.contacts.email}}</td>
                            <td>{{campaign_msgs.contacts.phone}}</td>


                        </tr>
                        {% empty %}
                        <h4 class="text-center m-5">No Data Found!</h4>
                        {% endfor %}


                    </tbody>
                </table>
            </div>
            <div class="dataTable-bottom mt-3" style="display: flex;
            flex-direction: row;
            justify-content: center;
            flex-wrap: wrap;">
                <nav class="dataTable-pagination">
                    <ul class="dataTable-pagination-list">



                        <li class="pager">
                            <a {% if camppaign_msgs_items_paginator.has_previous %}
                                href="/campaign-management/list-campaign/?page={{camppaign_msgs_items_paginator.previous_page_number}}"
                                {% else %} disabled="true" {% endif %}>
                                &lt;
                            </a>
                        </li>


                        {% for page in page_range %}
                        {% if page %}
                        {% if page == camppaign_msgs_items_paginator.number %}
                        <li class="active"><a href="#">{{ page }}</a></li>
                        {% else %}
                        {% if page == "First" %}
                        <li>
                            <a href="/campaign-management/list-campaign/?page=1">{{page}}</a>
                        </li>
                        {% elif page == "Last" %}
                        <li>
                            <a
                                href="/campaign-management/list-campaign/?page={{camppaign_msgs_items_paginator.paginator.num_pages}}">{{page}}</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="/campaign-management/list-campaign/?page={{page}}">{{page}}</a>
                        </li>
                        {% endif %}
                        {% endif %}
                        {% endif %}
                        {% endfor %}


                        <li class="pager">
                            <a {% if camppaign_msgs_items_paginator.has_next %}
                                href="/campaign-management/list-campaign/?page={{camppaign_msgs_items_paginator.next_page_number}}"
                                {% else %} disabled="true" {% endif %}>
                                &gt;
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>

        </div>
        <div class="mb-5"></div>
    </div>
</main>



{% endblock body %}

templates/list_contacts.html
{% extends "base.html" %}

{% block title %}
<title>list contacts</title>
{% endblock title %}

{% block body %}

<main>
    <div class="container-xl px-5">
        <div class="d-flex mt-4 mb-2 align-items-center">
            <h1 class="mb-0">Contacts</h1>
        </div>
        <div class="dataTable-wrapper dataTable-loading no-footer sortable searchable fixed-columns">
            {% if messages %}

            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }} col-md-12" {% endif %} role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}

            {% endif %}

            <div class="dataTable-top" style="width:100%">
                <div class="dataTable-dropdown mb-3">
                    <a href="{% url 'campaign_management:add_contact' %}"
                        style="text-decoration: none!important;"><button class="btn btn-success" type="button"><span
                                class="material-icons-outlined">
                                add
                            </span> Add Contact
                        </button></a>
                </div>
                
                      


                
                
                <!-- <div class="dataTable-search" style="width: 40%;">

                    <form id="syncBtn" method="GET" action="/campaign-management/sync-contacts/">
                        {% csrf_token %}
                        <button id="syncBtn" class="btn btn-success mb-3" type="submit">
                            Sync Contacts
                        </button>
                    </form>
                     -->

                     <div class="dataTable-search" style="width: 40%;">
                    <form id="syncForm" method="GET" action="/campaign-management/sync-contacts/">
                        {% csrf_token %}
                        <button id="syncBtn" class="btn btn-success mb-3" type="submit">
                            Sync Contacts
                        </button>
                    </form>
                    <p id="syncingMessage" class="text-muted" style="display: none;">
                        Contacts are syncing, please wait...
                    </p>
                    


                    

                    <form method="GET" action="">
                        <input class="dataTable-input" name="search_text" placeholder="Search conatcts....."
                            type="text">
                    </form>
                </div>
            </div>
            <div class="dataTable-container">
                <table id="datatablesSimple" class="dataTable-table">
                    <thead>
                        <tr>
                            <th><a href="#">Name </a></th>
                            <th><a href="#">Email</a></th>
                            <th><a href="#">Phone Number</a></th>
                            <th><a href="#">City</a></th>
                            <th><a href="#">Address</a></th>
                            <th><a href="#">Is IMS Contact</a></th>
                            <th><a href="#">Is Advertised Contact</a></th>
                            <th><a href="#">Created Date</a></th>
                            <th><a href="#">Updated Date</a></th>
                            <th><a href="#">Actions</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for contact in contacts_items_paginator %}
                        <tr>
                            <td>{{contact.name}}</td>
                            <td>{{contact.email}}</td>
                            <td>{{contact.phone}}</td>
                            <td>{{contact.city}}</td>
                            <td>{{contact.address}}</td>
                            <td>{{contact.is_ims_contact}}</td>
                            <td>{{contact.is_advertised_contact}}</td>
                            <td>{{contact.created_on}}</td>
                            <td>{{contact.updated_on}}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" id="dropdownMenuButton"
                                        type="button" data-bs-toggle="dropdown" aria-expanded="false"> Actions <i
                                            class="trailing-icon material-icons dropdown-caret">arrow_drop_down</i>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                                        <li>
                                            <a class="dropdown-item"
                                                href="{% url 'campaign_management:edit_contact' contact.id %}">
                                                <i class="material-icons-outlined leading-icon">edit</i>
                                                Edit
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item"
                                                href="{% url 'campaign_management:delete_contact' contact.id %}">
                                                <i class="material-icons-outlined leading-icon">delete</i>
                                                Delete
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                        {% empty %}
                        <h4 class="text-center m-5">No Data Found!</h4>
                        {% endfor %}


                    </tbody>
                </table>
            </div>
            <div class="dataTable-bottom mt-3" style="display: flex;
            flex-direction: row;
            justify-content: center;
            flex-wrap: wrap;
            color: rgb(84, 60, 107);">
                {{ total_contacts }} Contacts
            </div>
            
            <div class="dataTable-bottom mt-3" style="display: flex;
            flex-direction: row;
            justify-content: center;
            flex-wrap: wrap;">
                <nav class="dataTable-pagination">
                    <ul class="dataTable-pagination-list">



                        <li class="pager">
                            <a {% if contacts_items_paginator.has_previous %}
                                href="/campaign-management/list-contacts/?page={{contacts_items_paginator.previous_page_number}}"
                                {% else %} disabled="true" {% endif %}>
                                &lt;
                            </a>
                        </li>

                        
                        {% for page in page_range %}
                        {% if page %}
                        {% if page == contacts_items_paginator.number %}
                        <li class="active"><a href="#">{{ page }}</a></li>
                        {% else %}
                        {% if page == "First" %}
                        <li>
                            <a href="/campaign-management/list-contacts/?page=1">{{page}}</a>
                        </li>
                        {% elif page == "Last" %}
                        <li>
                            <a
                                href="/campaign-management/list-contacts/?page={{contacts_items_paginator.paginator.num_pages}}">{{page}}</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="/campaign-management/list-contacts/?page={{page}}">{{page}}</a>
                        </li>
                        {% endif %}
                        {% endif %}
                        {% endif %}
                        {% endfor %}


                        <li class="pager">
                            <a {% if contacts_items_paginator.has_next %}
                                href="/campaign-management/list-contacts/?page={{contacts_items_paginator.next_page_number}}"
                                {% else %} disabled="true" {% endif %}>
                                &gt;
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>

        </div>
        <div class="mb-5"></div>
    </div>
</main>
{% endblock body %}

{% block js %} 
<script>
    const syncBtn = document.getElementById("syncBtn");
    const syncingMessage = document.getElementById("syncingMessage");
    const syncForm = document.getElementById("syncForm");

    syncForm.addEventListener("submit", function (event) {
        // event.preventDefault();
        syncBtn.disabled = true;
        syncingMessage.style.display = "block";

        // // Perform the actual sync operation (you might need to add AJAX or other code here)

        // // For demonstration purposes, let's simulate a delay of 3 seconds
        // setTimeout(function () {
        //     syncBtn.disabled = false;
        //     syncingMessage.style.display = "none";
        // }, 3000); // Change this value to your actual sync time in milliseconds
    });

    
</script>

{% endblock js %}

templates/list_prev_campaigns.html
{% extends "base.html" %}

{% block title %}
<title>list all campaigns</title>
{% endblock title %}

{% block body %}

<main>
    <div class="container-xl px-5">
        <div class="d-flex mt-4 mb-2 align-items-center">
            <h1 class="mb-0">All Campaigns</h1>
        </div>
        <div class="dataTable-wrapper dataTable-loading no-footer sortable searchable fixed-columns">
            {% if messages %}

            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }} col-md-12" {% endif %} role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}

            {% endif %}

 
            <div class="dataTable-container">
                <table id="datatablesSimple" class="dataTable-table">
                    <thead>
                        <tr>
                            <th><a href="#">Name </a></th>
                            <th><a href="#">Type</a></th>
                            <th><a href="#">Status</a></th>
                            <th><a href="#">Date Time</a></th>
                            <th><a href="#">Email Subject</a></th>
                            <th><a href="#">Email Body</a></th>
                            <th><a href="#">SMS Body</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cmpaign in campaigns_items_paginator %}
                        <tr>
                            <td>{{cmpaign.name}}</td>
                            <td>{{cmpaign.type}}</td>
                            <td>{{cmpaign.status}}</td>
                            <td>{{cmpaign.campaign_datetime}}</td>
                            <td>{{cmpaign.email_subject}}</td>
                            <td>{{cmpaign.email_body|safe  }}</td>
                            <td>{{cmpaign.sms_body}}</td>
                          
       

                        </tr>
                        {% empty %}
                        <h4 class="text-center m-5">No Data Found!</h4>
                        {% endfor %}


                    </tbody>
                </table>
            </div>
            <div class="dataTable-bottom mt-3" style="display: flex;
            flex-direction: row;
            justify-content: center;
            flex-wrap: wrap;
            color: rgb(84, 60, 107);">
                {{ total_campaigns }} Campaigns
            </div>

            <div class="dataTable-bottom mt-3" style="display: flex;
            flex-direction: row;
            justify-content: center;
            flex-wrap: wrap;">
                <nav class="dataTable-pagination">
                    <ul class="dataTable-pagination-list">



                        <li class="pager">
                            <a {% if campaigns_items_paginator.has_previous %}
                                href="/campaign-management/list-prev-campaigns/?page={{campaigns_items_paginator.previous_page_number}}"
                                {% else %} disabled="true" {% endif %}>
                                &lt;
                            </a>
                        </li>


                        {% for page in page_range %}
                        {% if page %}
                        {% if page == campaigns_items_paginator.number %}
                        <li class="active"><a href="#">{{ page }}</a></li>
                        {% else %}
                        {% if page == "First" %}
                        <li>
                            <a href="/campaign-management/list-prev-campaigns/?page=1">{{page}}</a>
                        </li>
                        {% elif page == "Last" %}
                        <li>
                            <a
                                href="/campaign-management/list-prev-campaigns/?page={{campaigns_items_paginator.paginator.num_pages}}">{{page}}</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="/campaign-management/list-prev-campaigns/?page={{page}}">{{page}}</a>
                        </li>
                        {% endif %}
                        {% endif %}
                        {% endif %}
                        {% endfor %}


                        <li class="pager">
                            <a {% if campaigns_items_paginator.has_next %}
                                href="/campaign-management/list-prev-campaigns/?page={{campaigns_items_paginator.next_page_number}}"
                                {% else %} disabled="true" {% endif %}>
                                &gt;
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>

        </div>
        <div class="mb-5"></div>
    </div>
</main>
{% endblock body %}

{% block js %}
<script>
    const syncBtn = document.getElementById("syncBtn");
    const syncingMessage = document.getElementById("syncingMessage");
    const syncForm = document.getElementById("syncForm");

    syncForm.addEventListener("submit", function (event) {
        // event.preventDefault();
        syncBtn.disabled = true;
        syncingMessage.style.display = "block";

        // // Perform the actual sync operation (you might need to add AJAX or other code here)

        // // For demonstration purposes, let's simulate a delay of 3 seconds
        // setTimeout(function () {
        //     syncBtn.disabled = false;
        //     syncingMessage.style.display = "none";
        // }, 3000); // Change this value to your actual sync time in milliseconds
    });


</script>

{% endblock js %}